### ISSUE TITLE
Transfer `jupyterlab-filesystem-access`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-contrib.github.io#31]
# Target

`jupyterlab-filesystem-access` lets JupyterLab users browse local files using the (non-standard) Web Browser File System Access API: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

- The code repository: https://github.com/jtpio/jupyterlab-filesystem-access/
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/jupyterlab-filesystem-access
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-filesystem-access/
- The conda-forge recipe on https://github.com/conda-forge (if available): N/A
- The documentation website (if available): N/A

# Reason

Visibility, discoverability and shared maintenance.

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [x] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [x] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online (not yet: https://github.com/jtpio/jupyterlab-filesystem-access/issues/24)
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by jtpio** [comment]
cc @martinRenou

**Comment by jtpio** [comment]
@martinRenou @fcollonval both of you have been added as owners for the PyPI package.

**Comment by jtpio** [comment]
### TODO

- [ ] Transfer repo
- [ ] Add collaborators on PyPI
- [ ] Add package on npm

**Comment by jtpio** [comment]
All done, closing!
